---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
elasticsearch.url: http://elasticsearch:9200
xpack.infra.sources.default.fields.message: ["message","@message","e.RenderedMessage"]
xpack.infra.sources.default.logAlias: filebeat-*,kibana_sample_data_logs*,eshops-*